### ISSUE TITLE
EPUBファイルのリンクが404

### ISSUE THREAD

**Issue by ootaharuki99** [SunProIO/SunPro-techbookfest#4]
[SunPro 2016技術書典](https://sunpro.io/techbookfest/)の[EPUBファイルへのリンク](https://github.com/hakatashi/SunPro-techbookfest/releases/download/201606200157/techbookfest.ebub)にタイポがあるため、アクセスできません。

❌ `https://.../techbookfest.ebub`
✔️ `https://.../techbookfest.epub`

**Comment by hakatashi** [comment]
お恥ずかしい⋯⋯! ありがとうございます!
